server:
  port: 9999
#  servlet:
#    path: /eureka

eureka:
  instance:
    hostname: localhost
    #Eureka实例的状态页面和运行状况指示
#    status-page-url: ${server.servlet.path}/info
#    health-check-url-path: ${server.servlet.path}/health
  client:
    #禁止注册自己
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    #自我保护模式关闭
    enable-self-preservation: false