server:
  port: 9997
spring:
  application:
    name: admin-server

# tag::configuration-eureka[]
eureka:   #<1>
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health #2.0后actuator的地址发生了变化
  client:
    registryFetchIntervalSeconds: 5

# 2.0开始，actuator默认不开放，所以要设置为开发
management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS

# end::configuration-eureka[]

# admin登录的用户名和密码
spring:
  profiles: secure
  security:
    user:
      name: "admin"
      password: "123456"

# 注册给eureka的时候告诉eureka自己的密码
eureka:
  instance:
    metadata-map:
      "user.name": "admin"         #These two are needed so that the server
      "user.password": "123456" #can access the protected client endpoints