#logging:
#  level:
#    org.springframework.security: INFO

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000
#公共配置文件所有配置文件默认继承
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/

#endpoints:
#  health:
#    sensitive: false
#    enabled: true
#  actuator:
#    enabled: true
#    sensitive: false
#  beans:
#    sensitive: false
#    enabled: true

#关闭服务监控信息Actuator的安全验证
management:
  security:
    enabled: false
#feign调用开启Hystrix
feign:
  hystrix:
    enabled: true


