server:
  port: 7001


spring:
  zipkin:
    base-url: http://localhost:8001

#  rabbitmq:
#    host: localhost
#    port: 5672
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://112.74.38.117:3306/springboot?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  #rabbitmq:
   # host: localhost
   # port: 5672
    #username: guest
    #password: guest
    #publisher-confirms: true
    #virtual-host: /

foo: foo version 1