server:
  port: 7001

spring:
  #指定zipkin服务地址
  zipkin:
    base-url: http://localhost:8001
  boot:
    admin:
      client:
        url: "http://localhost:9997"
#  rabbitmq:
#    host: localhost
#    port: 5672
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://112.74.38.117:3306/springcloud?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&&useSSL=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  #rabbitmq:
   # host: localhost
   # port: 5672
    #username: guest
    #password: guest
    #publisher-confirms: true
    #virtual-host: /
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
      health:
        show-details: ALWAYS
foo: foo version 1