spring:
  redis:
    host: localhost
    port: 6379
#    password: 123456
    datebase: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 5
        min-idle: 0
        max-wait: 1000
server:
  port: 9999